// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBplD7jaZSr87Z_Xw7NE7QLS36oe2sSg8Y',
    appId: '1:1003417146683:web:1782520d04f3b599e6931e',
    messagingSenderId: '1003417146683',
    projectId: 'garbage-f583a',
    authDomain: 'garbage-f583a.firebaseapp.com',
    storageBucket: 'garbage-f583a.appspot.com',
    measurementId: 'G-CRF97PZLCR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBna-_rxFioMtvSaURukJoJPF2OYNuIikc',
    appId: '1:1003417146683:android:45bdedfd1635b52fe6931e',
    messagingSenderId: '1003417146683',
    projectId: 'garbage-f583a',
    storageBucket: 'garbage-f583a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRBXGBF7hlAHgwGC-ZqHhe-woltexNTVI',
    appId: '1:1003417146683:ios:e9aab38734e98af9e6931e',
    messagingSenderId: '1003417146683',
    projectId: 'garbage-f583a',
    storageBucket: 'garbage-f583a.appspot.com',
    iosBundleId: 'com.example.garbageManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRBXGBF7hlAHgwGC-ZqHhe-woltexNTVI',
    appId: '1:1003417146683:ios:b2ae76759637688ce6931e',
    messagingSenderId: '1003417146683',
    projectId: 'garbage-f583a',
    storageBucket: 'garbage-f583a.appspot.com',
    iosBundleId: 'com.example.garbageManagement.RunnerTests',
  );
}
